[package]
name = "UltimateT3"
version = "0.1.0"
authors = ["Luke Emery-Fertitta <lemeryfertitta@gmail.com>"]
edition = "2021"

[dependencies]
env_logger = "*"
futures-util = "*"
log = "*"
tokio = { version = "1.35.1", features = ["full"] }
tokio-tungstenite = "*"